name: test of metacapture LaTeX package.

on:
  push:
    paths:
      'metacapture/**'
  pull_request:
    paths:
      'metacapture/**'

permissions:
  contents: read

jobs:
  latex_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: "pip"
    - name: Install texlive
      uses: zauguin/install-texlive@v4
      with:
        package_file: .github/workflows/texlive.packages
    - name: Get TeXLive version
      run: | 
         tlmgr --version
         tlmgr update --all
    - name: Install dependencies
      working-directory: metacapture/tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest pdfplumber pdfminer python-xmp-toolkit nameparser xmp pylatexenc pypdf
    - name: Tests for metacapture.sty
      working-directory: metacapture/tests
      run: |
        echo "/usr/local/texlive/2025/bin/x86_64-linux/" >> "$GITHUB_PATH"
        python -m pytest compile_tests.py::test38_test -vv
